create table performers
(
    name varchar(50) not null,
    dob  date        not null,
    primary key (name, dob)
);

INSERT INTO dbs.performers (name, dob) VALUES ('Adams Bellringer', '2019-09-29');
INSERT INTO dbs.performers (name, dob) VALUES ('Adan Deem', '2019-04-19');
INSERT INTO dbs.performers (name, dob) VALUES ('Alberta Farry', '2019-10-05');
INSERT INTO dbs.performers (name, dob) VALUES ('Allie Cathesyed', '2018-12-18');
INSERT INTO dbs.performers (name, dob) VALUES ('Ania Hepher', '2018-12-05');
INSERT INTO dbs.performers (name, dob) VALUES ('Bad Bunny', '1993-02-02');
INSERT INTO dbs.performers (name, dob) VALUES ('Bartram Uman', '2019-02-21');
INSERT INTO dbs.performers (name, dob) VALUES ('Bertie Woodhead', '2019-05-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Carita Johanning', '2019-02-21');
INSERT INTO dbs.performers (name, dob) VALUES ('Cary Pien', '2019-05-08');
INSERT INTO dbs.performers (name, dob) VALUES ('Catha Tassaker', '2019-03-17');
INSERT INTO dbs.performers (name, dob) VALUES ('Charley de Wilde', '2019-03-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Clarette Dunkerly', '2019-07-04');
INSERT INTO dbs.performers (name, dob) VALUES ('Cobbie Lebbon', '2019-10-28');
INSERT INTO dbs.performers (name, dob) VALUES ('Con Moroney', '2019-01-17');
INSERT INTO dbs.performers (name, dob) VALUES ('Courteney Cox', '1964-06-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Danica Fright', '2019-04-06');
INSERT INTO dbs.performers (name, dob) VALUES ('Darin Antoniat', '2019-06-27');
INSERT INTO dbs.performers (name, dob) VALUES ('David Schwimmer', '1966-11-02');
INSERT INTO dbs.performers (name, dob) VALUES ('Denny Soughton', '2019-09-14');
INSERT INTO dbs.performers (name, dob) VALUES ('Devin Paal', '2018-12-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Dorelle Lindholm', '2018-12-14');
INSERT INTO dbs.performers (name, dob) VALUES ('Eddy Liffe', '2019-10-18');
INSERT INTO dbs.performers (name, dob) VALUES ('Eirena McAndrew', '2019-11-23');
INSERT INTO dbs.performers (name, dob) VALUES ('Elsie Bristo', '2019-06-10');
INSERT INTO dbs.performers (name, dob) VALUES ('Emery Ceresa', '2019-04-11');
INSERT INTO dbs.performers (name, dob) VALUES ('Erika Clemendet', '2018-12-03');
INSERT INTO dbs.performers (name, dob) VALUES ('Etta Matejka', '2019-10-26');
INSERT INTO dbs.performers (name, dob) VALUES ('Fanchette Chantree', '2019-01-14');
INSERT INTO dbs.performers (name, dob) VALUES ('Fee Mifflin', '2019-11-14');
INSERT INTO dbs.performers (name, dob) VALUES ('Fielding Carleton', '2019-03-13');
INSERT INTO dbs.performers (name, dob) VALUES ('Georgi Sorrie', '2019-02-07');
INSERT INTO dbs.performers (name, dob) VALUES ('Germana Campe', '2019-11-17');
INSERT INTO dbs.performers (name, dob) VALUES ('Glory Lygoe', '2019-04-25');
INSERT INTO dbs.performers (name, dob) VALUES ('Goldi Shelper', '2019-11-22');
INSERT INTO dbs.performers (name, dob) VALUES ('Ice Cube', '1969-06-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Ileana Osler', '2019-06-04');
INSERT INTO dbs.performers (name, dob) VALUES ('Ilise Burtonwood', '2019-03-31');
INSERT INTO dbs.performers (name, dob) VALUES ('Iver Wetwood', '2018-12-28');
INSERT INTO dbs.performers (name, dob) VALUES ('Jaimie Spleving', '2018-12-03');
INSERT INTO dbs.performers (name, dob) VALUES ('Janifer Pennells', '2019-05-06');
INSERT INTO dbs.performers (name, dob) VALUES ('Jennifer Aniston', '1969-02-11');
INSERT INTO dbs.performers (name, dob) VALUES ('Jock Trineman', '2019-07-30');
INSERT INTO dbs.performers (name, dob) VALUES ('John Lee Hooker', '1917-08-22');
INSERT INTO dbs.performers (name, dob) VALUES ('Jourdain Brayford', '2019-08-28');
INSERT INTO dbs.performers (name, dob) VALUES ('Juieta Kardos-Stowe', '2019-08-12');
INSERT INTO dbs.performers (name, dob) VALUES ('Julian Hugues', '2019-05-29');
INSERT INTO dbs.performers (name, dob) VALUES ('Julianne Nind', '2019-11-21');
INSERT INTO dbs.performers (name, dob) VALUES ('Kaitlyn Varlow', '2019-05-11');
INSERT INTO dbs.performers (name, dob) VALUES ('Kamila Woolward', '2019-01-10');
INSERT INTO dbs.performers (name, dob) VALUES ('Kimbell Hulle', '2019-05-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Laura d''Arcy', '2019-10-05');
INSERT INTO dbs.performers (name, dob) VALUES ('Leanora Sukbhans', '2019-03-20');
INSERT INTO dbs.performers (name, dob) VALUES ('Lek Antoney', '2019-10-26');
INSERT INTO dbs.performers (name, dob) VALUES ('Lilias Couldwell', '2019-09-12');
INSERT INTO dbs.performers (name, dob) VALUES ('Lillian Gamwell', '2019-11-29');
INSERT INTO dbs.performers (name, dob) VALUES ('Linda Fiorentino', '1958-03-09');
INSERT INTO dbs.performers (name, dob) VALUES ('Lisa Kudrow', '1963-07-30');
INSERT INTO dbs.performers (name, dob) VALUES ('Ludovika Palke', '2019-04-10');
INSERT INTO dbs.performers (name, dob) VALUES ('Luise Denekamp', '2019-09-09');
INSERT INTO dbs.performers (name, dob) VALUES ('Mahala Moles', '2019-11-08');
INSERT INTO dbs.performers (name, dob) VALUES ('Marc Anthony', '1992-01-01');
INSERT INTO dbs.performers (name, dob) VALUES ('Marguerite Stallibrass', '2019-11-22');
INSERT INTO dbs.performers (name, dob) VALUES ('Mark Wahlberg', '1971-06-05');
INSERT INTO dbs.performers (name, dob) VALUES ('Matt LeBlanc', '1967-07-25');
INSERT INTO dbs.performers (name, dob) VALUES ('Matthew Perry', '1968-08-19');
INSERT INTO dbs.performers (name, dob) VALUES ('Mitch Serrels', '2019-08-10');
INSERT INTO dbs.performers (name, dob) VALUES ('Mitchel Mulvagh', '2019-05-01');
INSERT INTO dbs.performers (name, dob) VALUES ('Nikos Maiden', '2019-11-11');
INSERT INTO dbs.performers (name, dob) VALUES ('Octavia Cathesyed', '2019-08-26');
INSERT INTO dbs.performers (name, dob) VALUES ('Oneida Smales', '2019-05-12');
INSERT INTO dbs.performers (name, dob) VALUES ('Osbourn Livesey', '2019-10-09');
INSERT INTO dbs.performers (name, dob) VALUES ('Paco Duling', '2019-06-01');
INSERT INTO dbs.performers (name, dob) VALUES ('Quentin Callam', '2019-03-05');
INSERT INTO dbs.performers (name, dob) VALUES ('Raeann Ivanov', '2019-10-14');
INSERT INTO dbs.performers (name, dob) VALUES ('Rick Ripsher', '2019-02-28');
INSERT INTO dbs.performers (name, dob) VALUES ('Roberto Bessent', '2019-08-10');
INSERT INTO dbs.performers (name, dob) VALUES ('Ruthie Fortie', '2019-09-08');
INSERT INTO dbs.performers (name, dob) VALUES ('Sabrina Pennaman', '2019-08-29');
INSERT INTO dbs.performers (name, dob) VALUES ('Selina Daughton', '2019-02-13');
INSERT INTO dbs.performers (name, dob) VALUES ('Sonja Loisi', '2019-09-26');
INSERT INTO dbs.performers (name, dob) VALUES ('Stepha Braban', '2019-02-01');
INSERT INTO dbs.performers (name, dob) VALUES ('Suzie Rayer', '2018-12-27');
INSERT INTO dbs.performers (name, dob) VALUES ('Tam Deveral', '2019-07-29');
INSERT INTO dbs.performers (name, dob) VALUES ('Tedman Lorentz', '2019-06-06');
INSERT INTO dbs.performers (name, dob) VALUES ('Tommy Lee Jones', '1946-09-15');
INSERT INTO dbs.performers (name, dob) VALUES ('Trenna Venables', '2019-06-14');
INSERT INTO dbs.performers (name, dob) VALUES ('Trixy Mattingley', '2019-08-26');
INSERT INTO dbs.performers (name, dob) VALUES ('Vance Flecknell', '2019-02-18');
INSERT INTO dbs.performers (name, dob) VALUES ('Vergil Glanvill', '2019-06-11');
INSERT INTO dbs.performers (name, dob) VALUES ('Vincent D''Onofrio', '1959-06-30');
INSERT INTO dbs.performers (name, dob) VALUES ('Wallache Mackelworth', '2019-05-03');
INSERT INTO dbs.performers (name, dob) VALUES ('Will Smith', '1968-09-25');
INSERT INTO dbs.performers (name, dob) VALUES ('Yule Ormrod', '2019-10-03');
INSERT INTO dbs.performers (name, dob) VALUES ('Zonda Rewan', '2019-07-14');